FROM nginx:alpine

# Copiar arquivo HTML
# Copiar todos os arquivos estáticos
COPY . /usr/share/nginx/html/

# Copiar configuração do nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]