FROM node:latest AS builder

WORKDIR /app

RUN npm install ci

RUN npm ci

COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]