FROM nginx:alpine

# Copiar arquivo HTML
COPY index.html /usr/share/nginx/html/index.html

# Copiar configuração do nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]