services:
  #====================VAULT========================#
  vault:
    build:
      context: ./app/vault
      dockerfile: dockerfile
    container_name: vault
    volumes:
      - vault_data:/vault/data
      - vault_logs:/vault/logs
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - SKIP_SETCAP=true
    cap_add:
      - IPC_LOCK
    networks:
      - minibank-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:8200/v1/sys/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # ====================POSTGRES========================#
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: minibank_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh:ro
    networks:
      - minibank-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d minibank_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  #==================== AUTH SERVICE  ====================
  auth_service:
    build:
      context: ./app/services/auth
      dockerfile: dockerfile
    container_name: auth_service
    environment:
      VAULT_ADDR: http://vault:8200
      SERVICE_NAME: auth
    volumes:
      - vault_data:/vault-data:ro
    depends_on:
      vault:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - minibank-network
    restart: unless-stopped

  # ==================== USER SERVICE  ====================
  user_service:
    build:
      context: ./app/services/user
      dockerfile: dockerfile
    container_name: user_service
    environment:
      VAULT_ADDR: http://vault:8200
      SERVICE_NAME: user
    volumes:
      - vault_data:/vault-data:ro
    depends_on:
      vault:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - minibank-network
    restart: unless-stopped

  # ==================== TRANSITION SERVICE  ====================
  transition_service:
    build:
      context: ./app/services/transition
      dockerfile: dockerfile
    container_name: transition_service
    environment:
      VAULT_ADDR: http://vault:8200
      SERVICE_NAME: transition
    volumes:
      - vault_data:/vault-data:ro
    depends_on:
      vault:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - minibank-network
    restart: unless-stopped

  # ==================== BLOCKCHAIN SERVICE  ====================
  blockchain_service:
    build:
      context: ./app/services/blockchain
      dockerfile: dockerfile
    container_name: blockchain_service
    environment:
      VAULT_ADDR: http://vault:8200
      SERVICE_NAME: blockchain
    volumes:
      - vault_data:/vault-data:ro
    depends_on:
      vault:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - minibank-network
    restart: unless-stopped

  # ==================== NGINX WAF====================
  nginx:
    build:
      context: ./app
      dockerfile: nginx/dockerfile
    container_name: nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - nginx_certs:/etc/nginx/certs
    depends_on:
      - auth_service
      - user_service
      - transition_service
      - blockchain_service
    networks:
      - minibank-network
    restart: unless-stopped

networks:
  minibank-network:
    driver: bridge

volumes:
  postgres_data:
  nginx_certs:
  vault_data:
  vault_logs: