FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache curl netcat-openbsd

COPY package.json ./

RUN npm install

COPY src ./src

RUN mkdir -p artifacts/contracts

EXPOSE 3004

CMD ["node", "src/blockchain.js"]
