FROM owasp/modsecurity-crs:nginx-alpine

# Copiar configurações customizadas
COPY nginx.conf /etc/nginx/nginx.conf
COPY modsecurity.conf /etc/nginx/modsecurity/modsecurity.conf

# Copiar script de inicialização
COPY --chmod=755 docker-entrypoint.sh /docker-entrypoint.sh

EXPOSE 80 443

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]