FROM owasp/modsecurity-crs:nginx-alpine

RUN mkdir -p /etc/nginx/certs && \
    mkdir -p /var/log && \
    chown -R nginx:nginx /etc/nginx/certs && \
    chown -R nginx:nginx /var/log

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/nginx/certs/nginx-selfsigned.key \
    -out /etc/nginx/certs/nginx-selfsigned.crt \
    -subj "/C=BR/ST=SP/L=SaoPaulo/O=FtTranscendence/CN=localhost" && \
    chmod 644 /etc/nginx/certs/nginx-selfsigned.crt && \
    chmod 600 /etc/nginx/certs/nginx-selfsigned.key

# Copiar configurações customizadas
COPY nginx.conf /etc/nginx/nginx.conf
COPY modsecurity.conf /etc/nginx/modsecurity/modsecurity.conf

# Copiar script de inicialização
COPY --chmod=755 docker-entrypoint.sh /docker-entrypoint.sh

EXPOSE 80 443

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]