global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx_exporter:9113"]

  - job_name: "auth_service"
    metrics_path: /metrics
    static_configs:
      - targets: ["auth_service:3001"]

  - job_name: "user_service"
    metrics_path: /metrics
    static_configs:
      - targets: ["user_service:3002"]

  - job_name: "transition_service"
    metrics_path: /metrics
    static_configs:
      - targets: ["transition_service:3003"]

  - job_name: "blockchain_service"
    metrics_path: /metrics
    static_configs:
      - targets: ["blockchain_service:3004"]
