FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache python3 make g++ git netcat-openbsd

COPY package.json ./

RUN npm install

COPY hardhat.config.js ./

RUN mkdir -p test cache artifacts

EXPOSE 8545

CMD ["npx", "hardhat", "node", "--hostname", "0.0.0.0"]